name: unicons
description: 1000+ beautiful icons to use in you dream project, with all the customization Flutter provides
# author: Pedro Lemos <lemozxpedro@gmail.com>
homepage: https://github.com/pedrolemoz/unicons-flutter

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart:

flutter:
  fonts:
    - family: UniconsLine
      fonts:
      - asset:  icons/UniconsLine.ttf
    
    - family: UniconsSolid
      fonts:
      - asset:  icons/UniconsSolid.ttf