name: unicons
description: 1000+ Pixel-perfect vector icons and Iconfont for your next project.
# author: Pedro Lemos <lemozxpedro@gmail.com>
homepage: https://github.com/pedrolemoz/unicons-flutter

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: UniconsLine
      fonts:
      - asset:  icons/UniconsLine.ttf
    
    - family: UniconsSolid
      fonts:
      - asset:  icons/UniconsSolid.ttf